version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dotnet-all:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/LittleHelpers.Web"
    schedule:
      interval: "weekly"
    groups:
      npm-all:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docker-all:
        patterns:
          - "*"

  - package-ecosystem: "docker-compose"
    directory: "/docs/compose"
    schedule:
      interval: "weekly"
    groups:
      compose-all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-all:
        patterns:
          - "*"
