// <auto-generated />
using System;
using LittleHelpers.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LittleHelpers.ApiService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LittleHelpers.ApiService.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxTimesPerDay")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTimesPerWeek")
                        .HasColumnType("integer");

                    b.Property<int?>("MinDaysBetween")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Chores");
                });

            modelBuilder.Entity("LittleHelpers.ApiService.Models.ChoreAssignment", b =>
                {
                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ChoreId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChoreAssignments");
                });

            modelBuilder.Entity("LittleHelpers.ApiService.Models.ChoreLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoreId")
                        .HasColumnType("integer");

                    b.Property<string>("ChoreName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PerformedBy")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ChoreLogs");
                });

            modelBuilder.Entity("LittleHelpers.ApiService.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MonthlyAllowance")
                        .HasColumnType("numeric");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PointsGoal")
                        .HasColumnType("integer");

                    b.Property<string>("UserLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LittleHelpers.ApiService.Models.ChoreAssignment", b =>
                {
                    b.HasOne("LittleHelpers.ApiService.Models.Chore", "Chore")
                        .WithMany("ChoreAssignments")
                        .HasForeignKey("ChoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LittleHelpers.ApiService.Models.User", "User")
                        .WithMany("ChoreAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LittleHelpers.ApiService.Models.Chore", b =>
                {
                    b.Navigation("ChoreAssignments");
                });

            modelBuilder.Entity("LittleHelpers.ApiService.Models.User", b =>
                {
                    b.Navigation("ChoreAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
